# =============================================================================
# Makefile for gamesheet-sdk-py
# -----------------------------------------------------------------------------
# Unified developer interface around the tooling described in CLAUDE.md.
# Run `make help` (or just `make`) for the full target list.
# =============================================================================

SHELL          := /bin/bash
.DEFAULT_GOAL  := help
MAKEFLAGS      += --no-print-directory

# --- Python interpreter detection --------------------------------------------
# Probe /usr/bin for python3 + python3.1X binaries and pick the highest
# version-sorted name. Override on the command line: `make PYTHON=python3.12`.

DETECTED_PYTHON := $(shell basename -a /usr/bin/python3{,.1[0-9]} 2>/dev/null \
				| grep -E '^python3(\.[0-9]+)?$$' \
				| sort -V \
				| tail -n1)
PYTHON         ?= $(or $(DETECTED_PYTHON),python3)

# --- Standard paths ----------------------------------------------------------

VENV           := .venv
PKG            := src/gamesheet_sdk
DOCS_BUILD     := docs/_build
DOCS_AUTOSUM   := docs/_autosummary

# --- ANSI colors (used by help + status lines) -------------------------------

CYAN   := \033[36m
GREEN  := \033[32m
YELLOW := \033[33m
RED    := \033[31m
BOLD   := \033[1m
RESET  := \033[0m

# =============================================================================
# Help (default goal)
# =============================================================================

.PHONY: help
help: ## Show this help message
	@printf "$(BOLD)gamesheet-sdk-py$(RESET) — developer Makefile\n\n"
	@printf "$(BOLD)Usage:$(RESET) make $(CYAN)<target>$(RESET) [VAR=value ...]\n\n"
	@printf "$(BOLD)Variables:$(RESET)\n"
	@printf "  $(CYAN)%-20s$(RESET) %s (current: $(GREEN)%s$(RESET))\n" \
		"PYTHON"  "Python interpreter (auto-detected; override to pick a 3.11+ version)" "$(PYTHON)"
	@printf "  $(CYAN)%-20s$(RESET) %s (current: $(GREEN)%s$(RESET))\n" \
		"VENV"    "Virtualenv directory" "$(VENV)"
	@printf "\n$(BOLD)Targets:$(RESET)\n"
	@awk 'BEGIN {FS = ":.*?## "} \
			/^[a-zA-Z_-]+:.*?## / { \
			printf "  $(CYAN)%-20s$(RESET) %s\n", $$1, $$2 \
			}' $(MAKEFILE_LIST)
	@printf "\n$(BOLD)Pattern rules:$(RESET)\n"
	@printf "  $(CYAN)%-20s$(RESET) %s\n" \
		"venv-<extra>" "Create venv + install a single extra (e.g. venv-dev, venv-docs)"
	@printf "  $(CYAN)%-20s$(RESET) %s\n" \
		"tox-<env>"    "Run any tox env (e.g. tox-py312, tox-lint, tox-fix)"
	@printf "\n$(BOLD)Examples:$(RESET)\n"
	@printf "  $(YELLOW)make install$(RESET)            $(GREEN)# editable + dev extras + Playwright Chromium$(RESET)\n"
	@printf "  $(YELLOW)make venv-dev$(RESET)           $(GREEN)# fresh $(VENV) with [dev]$(RESET)\n"
	@printf "  $(YELLOW)make test-fast$(RESET)          $(GREEN)# skip @pytest.mark.browser tests$(RESET)\n"
	@printf "  $(YELLOW)make tox-py313$(RESET)          $(GREEN)# pytest under Python 3.13 only$(RESET)\n"
	@printf "  $(YELLOW)make PYTHON=python3.12 venv$(RESET)  $(GREEN)# pin venv interpreter$(RESET)\n"

# =============================================================================
# Installation
# =============================================================================

.PHONY: install
install: ## Editable install with [dev] extras + Playwright Chromium
	pip install -e ".[dev]"
	python -m playwright install chromium

# =============================================================================
# Cleaning
# -----------------------------------------------------------------------------
# Notes:
#   - The package version is derived from `git describe` via hatch-vcs; no
#     clean target touches `.git/` or `src/gamesheet_sdk/_version.py` (the
#     latter is regenerated by hatch on the next build anyway).
# =============================================================================

.PHONY: clean
clean: ## Remove caches and build artifacts (preserves Git/hatch-vcs state)
	@printf "$(CYAN)→$(RESET) clean: __pycache__, .pytest_cache, .mypy_cache, .coverage, dist/, coverage.xml\n"
	@find . -type d -name '__pycache__' -prune -exec rm -rf {} +
	@rm -rf .pytest_cache .mypy_cache .coverage dist coverage.xml

.PHONY: clean-all
clean-all: clean ## clean + remove .tox, $(VENV), and docs build dirs
	@printf "$(CYAN)→$(RESET) clean-all: .tox, $(VENV), $(DOCS_BUILD), $(DOCS_AUTOSUM)\n"
	@rm -rf .tox $(VENV) $(DOCS_BUILD) $(DOCS_AUTOSUM)

# =============================================================================
# Virtual environments
# -----------------------------------------------------------------------------
# Both `venv` and `venv-<extra>` start from a clean slate — they wipe any
# existing $(VENV) first, then build with the detected (or overridden) PYTHON.
# =============================================================================

.PHONY: venv
venv: ## Create a fresh $(VENV) using $(PYTHON) (no project install)
	@printf "$(CYAN)→$(RESET) creating $(VENV) with $(GREEN)$(PYTHON)$(RESET)\n"
	@rm -rf $(VENV)
	$(PYTHON) -m venv $(VENV)
	@$(VENV)/bin/pip install --quiet --upgrade pip
	@printf "$(GREEN)✓$(RESET) $(VENV) ready. Activate with: $(YELLOW)source $(VENV)/bin/activate$(RESET)\n"

.PHONY: venv-%
venv-%: ## Create $(VENV) and install the named extra (e.g., make venv-dev)
	@printf "$(CYAN)→$(RESET) creating $(VENV) with $(GREEN)$(PYTHON)$(RESET) + extra '$(GREEN)$*$(RESET)'\n"
	@rm -rf $(VENV)
	$(PYTHON) -m venv $(VENV)
	@$(VENV)/bin/pip install --quiet --upgrade pip
	$(VENV)/bin/pip install -e ".[$*]"
	@printf "$(GREEN)✓$(RESET) $(VENV) ready with [$*]. Activate with: $(YELLOW)source $(VENV)/bin/activate$(RESET)\n"

# =============================================================================
# Testing
# -----------------------------------------------------------------------------
# pytest is configured with --block-network (pytest-recording). Any test that
# opens a socket without a VCR cassette fails. test-fast skips the browser
# marker so you don't spin up real Chromium for the inner dev loop.
# =============================================================================

.PHONY: test
test: ## Run the full pytest suite (network-blocked; VCR + playwright)
	pytest

.PHONY: test-fast
test-fast: ## Run only fast tests (-m "not browser")
	pytest -m "not browser"

.PHONY: test-cov
test-cov: ## Run pytest with coverage (fail_under threshold lives in pyproject)
	pytest --cov

# =============================================================================
# Linting, formatting, typing
# -----------------------------------------------------------------------------
# `lint` runs the whole pre-commit suite. `type` runs mypy directly in --strict
# mode (the project is a PEP 561 typed package; new code must pass strict).
# =============================================================================

.PHONY: lint
lint: ## Run pre-commit across the whole repo (includes mypy --strict, ruff, xenon)
	pre-commit run --all-files

.PHONY: type
type: ## Run mypy --strict against src/ (PEP 561 typed package — strict required)
	mypy --strict $(PKG)

.PHONY: fix
fix: _check-tox ## Apply formatters in place (isort, black, mdformat)
	tox -e fix

# =============================================================================
# Complexity / metrics
# -----------------------------------------------------------------------------
# Xenon enforces the project-wide cyclomatic-complexity ceiling via pre-commit
# (--max-absolute=A --max-modules=A --max-average=B). `tox -e metrics` reports
# the actual radon numbers — useful before pushing a function that's growing
# conditionals.
# =============================================================================

.PHONY: metrics
metrics: _check-tox ## Radon + Xenon complexity gates (tox -e metrics)
	tox -e metrics

# =============================================================================
# Documentation (Sphinx + Furo theme)
# -----------------------------------------------------------------------------
# `docs` builds HTML two-pass (warm-up + strict -n -W). `docs-serve` runs
# sphinx-autobuild for live reload. `docs-pdf` requires LaTeX + latexmk on
# PATH; install texlive-latex-extra (or your distro's equivalent) first.
# =============================================================================

.PHONY: docs
docs: _check-tox ## Build HTML docs (Sphinx + Furo, two-pass strict)
	tox -e docs

.PHONY: docs-serve
docs-serve: _check-tox ## Live-reload preview of HTML docs (sphinx-autobuild)
	tox -e docs-serve

.PHONY: docs-pdf
docs-pdf: _check-tox ## Build PDF docs via LaTeX (needs pdflatex + latexmk on PATH)
	tox -e docs-pdf

.PHONY: docs-lint
docs-lint: _check-tox ## sphinx-lint over docs/ + API freshness check
	tox -e docs-lint

.PHONY: docs-api
docs-api: ## Generate API documentation using sphinx-apidoc
	python docs/generate_api_docs.py

.PHONY: docs-check
docs-check: ## Check if API docs are up-to-date with source
	python docs/check_api_freshness.py

.PHONY: docs-linkcheck
docs-linkcheck: _check-tox ## Check external links in docs
	tox -e docs-linkcheck

# =============================================================================
# Tox pattern rule
# -----------------------------------------------------------------------------
# Escape hatch for any tox env not given a dedicated target above:
#   make tox-py312     →  tox -e py312
#   make tox-lint      →  tox -e lint
#   make tox-security  →  tox -e security
# =============================================================================

.PHONY: tox-%
tox-%: _check-tox ## Run any tox env (e.g., tox-py312, tox-lint, tox-fix)
	tox -e $*

.PHONY: _check-tox
_check-tox:
	@command -v tox >/dev/null 2>&1 || { \
		printf "$(RED)error:$(RESET) $(BOLD)tox$(RESET) is not on PATH.\n" >&2; \
		printf "  install it with: $(CYAN)make install$(RESET)  (or: $(CYAN)pip install tox$(RESET))\n" >&2; \
		exit 1; \
	}
