# Copyright (c) 2026 bdperkin
# SPDX-License-Identifier: MIT

"""Teams dashboard SDK for GameSheet."""

from gamesheet_sdk.teams.login import TeamsLoginFlow, refresh_access_token
from gamesheet_sdk.teams.lookups import LookupValue, list_lookups
from gamesheet_sdk.teams.schedule import (
    CalendarEventCreated,
    CalendarSubscription,
    CreatedGameResult,
    ScheduleDeleteResult,
    ScheduleEvent,
    ScheduleEventDetail,
    build_rrule,
    create_calendar_event_raw,
    create_event,
    create_game,
    create_practice,
    create_schedule_game_raw,
    delete_calendar_event,
    delete_calendar_event_raw,
    delete_calendar_occurrence,
    delete_calendar_occurrence_raw,
    delete_event,
    delete_game,
    delete_practice,
    delete_schedule_game_raw,
    fetch_availability_raw,
    fetch_calendar_raw,
    fetch_event_occurrence_raw,
    fetch_scheduled_game_raw,
    get_calendar_subscription,
    get_event,
    get_game,
    get_practice,
    get_schedule_event,
    list_events,
    list_games,
    list_practices,
    list_schedule,
    validate_game_type,
)
from gamesheet_sdk.teams.seasons import (
    PenaltyCode,
    SeasonDetail,
    SeasonSummary,
    SeasonTeam,
    fetch_seasons_raw,
    get_season,
    get_season_penalty_codes,
    get_season_teams,
    list_seasons,
)
from gamesheet_sdk.teams.session import TeamsAuthenticatedSession
from gamesheet_sdk.teams.teams import (
    TeamDetail,
    TeamSummary,
    archive_team,
    delete_team,
    fetch_team_raw,
    fetch_teams_raw,
    get_team,
    list_teams,
    restore_team,
    unarchive_team,
    update_team,
    upload_team_image,
)

__all__ = [
    "CalendarEventCreated",
    "CalendarSubscription",
    "CreatedGameResult",
    "LookupValue",
    "PenaltyCode",
    "ScheduleDeleteResult",
    "ScheduleEvent",
    "ScheduleEventDetail",
    "SeasonDetail",
    "SeasonSummary",
    "SeasonTeam",
    "TeamDetail",
    "TeamSummary",
    "TeamsAuthenticatedSession",
    "TeamsLoginFlow",
    "archive_team",
    "build_rrule",
    "create_calendar_event_raw",
    "create_event",
    "create_game",
    "create_practice",
    "create_schedule_game_raw",
    "delete_calendar_event",
    "delete_calendar_event_raw",
    "delete_calendar_occurrence",
    "delete_calendar_occurrence_raw",
    "delete_event",
    "delete_game",
    "delete_practice",
    "delete_schedule_game_raw",
    "delete_team",
    "fetch_availability_raw",
    "fetch_calendar_raw",
    "fetch_event_occurrence_raw",
    "fetch_scheduled_game_raw",
    "fetch_seasons_raw",
    "fetch_team_raw",
    "fetch_teams_raw",
    "get_calendar_subscription",
    "get_event",
    "get_game",
    "get_practice",
    "get_schedule_event",
    "get_season",
    "get_season_penalty_codes",
    "get_season_teams",
    "get_team",
    "list_events",
    "list_games",
    "list_lookups",
    "list_practices",
    "list_schedule",
    "list_seasons",
    "list_teams",
    "refresh_access_token",
    "restore_team",
    "unarchive_team",
    "update_team",
    "upload_team_image",
    "validate_game_type",
]
