# Copyright (c) 2026 bdperkin
# SPDX-License-Identifier: MIT

"""Static defaults and constants for pre-commit configuration generation."""

from __future__ import annotations

from shared import PROJECT_NAME

DEFAULT_CONFIG_FILE = ".genprecommitconfig.yaml"

DEFAULT_OUTPUT_FILE = ".pre-commit-config.yaml"

DEFAULT_LANGUAGE_VERSION: dict[str, str] = {"python": "python3.11"}

DEFAULT_STAGES: list[str] = ["pre-commit", "pre-push"]

DEFAULT_FAIL_FAST: bool = True

DEFAULT_MAX_DOWNGRADE_ATTEMPTS: int = 3

DEFAULT_ALLOWED_LANGUAGES: list[str] = ["fail", "pygrep", "python", "script", "system"]

INIT_TEMPLATE = (
    "# .genprecommitconfig.yaml - Configuration for tools/genprecommitconfig\n"
    "#\n"
    "# Run: ./tools/genprecommitconfig\n"
    "# See: tools/README.md\n\n"
    "categories: {}\n"
)

FETCH_HOOKS_TIMEOUT = 15

PRE_COMMIT_RUN_TIMEOUT = 600


HOOK_TARGETING_KEYS: set[str] = {"always_run", "files", "stages", "types", "types_or"}

_SEP = "==============================================================================\n"
_SUBSEP = "----------------------------------------------------------------------------\n"

CI_SECTION_COMMENT = (
    "\n"
    + _SEP
    + "Pre-commit.ci Service Configuration\n"
    + _SEP
    + "Configuration for https://pre-commit.ci\n"
    + "Automates pre-commit hook version updates via GitHub integration.\n"
    + _SEP
    + "\n"
)

CI_PROPERTY_DESCRIPTIONS: dict[str, str] = {
    "autofix_prs": "Automatically pushes formatting fixes back to the PR branch.",
    "autofix_commit_msg": "The Git commit message used when autofixing code.",
    "autoupdate_schedule": "Frequency of dependency updates (weekly, monthly, quarterly).",
    "autoupdate_commit_msg": "The Git commit message used when updating hook tags.",
    "skip": "List of hook ids to skip only in CI (useful for heavy/slow local scripts).",
    "submodules": "Whether to recursively check out Git submodules in the CI environment.",
    "autoupdate_branch": "Branch to send autoupdate PRs to (empty string = default branch).",
}

GLOBALS_SECTION_COMMENT = "\n" + _SEP + "Global Defaults\n" + _SEP

GLOBALS_PROPERTY_DESCRIPTIONS: dict[str, str] = {
    "default_stages": "Restricts hooks to specific Git stages (e.g., [commit, push]).",
    "default_language_version": "Maps languages to precise runtime versions (e.g., python: python3.11).",
    "files": "Global regex pattern matching files to include in all checks.",
    "exclude": "Global regex pattern targeting files or directories to ignore.",
    "fail_fast": "If true, aborts the entire execution run after the first failed hook.",
    "minimum_pre_commit_version": "Enforces a specific minimum version of the local pre-commit binary.",
}

REPOS_SECTION_COMMENT = (
    "\n"
    + _SEP
    + "Hook Repositories\n"
    + _SEP
    + f"NOTE: Many hooks use `additional_dependencies: [{PROJECT_NAME}[<extras>]]`\n"
    + "to pull runtime deps into the isolated hook venv. This pattern consolidates\n"
    + "all tool dependencies in pyproject.toml's optional-dependencies groups as\n"
    + "the single source of truth.\n"
    + _SEP
    + "\n"
)

HEADER_COMMENT = (
    "NOTICE: DO NOT EDIT THIS FILE!\n"
    "This file is managed by './tools/genprecommitconfig'\n"
    "Modifications should be made in '.genprecommitconfig.yaml'\n\n"
    + _SEP
    + "Pre-Commit Hook Configuration\n"
    + _SEP
    + "Fast, local checks that run automatically before every git commit command.\n"
    + "See https://pre-commit.com for documentation and hook configuration options.\n"
    + _SEP
)
