# Copyright (c) 2026 bdperkin
# SPDX-License-Identifier: MIT

"""Test helper utilities."""

from __future__ import annotations

from tests.helpers.constants import (
    ASSOCIATION_ID,
    COACH_EXTERNAL_ID,
    COACH_EXTERNAL_ID_SECONDARY,
    COACH_EXTERNAL_ID_TERTIARY,
    COACH_FIRST_NAME,
    COACH_ID_PRIMARY,
    COACH_ID_QUATERNARY,
    COACH_ID_SECONDARY,
    COACH_ID_TERTIARY,
    COACH_LAST_NAME,
    DEFAULT_COACH_FIRST_NAME,
    DEFAULT_COACH_LAST_NAME,
    DEFAULT_PLAYER_FIRST_NAME,
    DEFAULT_PLAYER_LAST_NAME,
    DIVISION_ID,
    INVITATION_CODE,
    INVITATION_ID,
    JSONAPI_CONTENT_TYPE,
    LEAGUE_ID,
    PLAYER_EXTERNAL_ID,
    PLAYER_EXTERNAL_ID_SECONDARY,
    PLAYER_FIRST_NAME,
    PLAYER_ID,
    PLAYER_ID_QUATERNARY,
    PLAYER_ID_SECONDARY,
    PLAYER_ID_TERTIARY,
    PLAYER_LAST_NAME,
    PROTOTEAM_ID,
    REFEREE_EXTERNAL_ID_PRIMARY,
    REFEREE_EXTERNAL_ID_SECONDARY,
    REFEREE_EXTERNAL_ID_TERTIARY,
    REFEREE_EXTERNAL_ID_TEST,
    SEASON_EXTERNAL_ID,
    SEASON_ID,
    TEAM_ID,
    TEAM_ID_SECONDARY,
    TEST_BASE_URL,
    TEST_EMAIL_GENERIC,
    TEST_EMAIL_MINIMAL,
    TEST_EMAIL_REFEREE,
    TIMESTAMP_2024_01_01,
    TIMESTAMP_2024_09_01,
)
from tests.helpers.mocks import (
    setup_get_team_roster_mocks,
    setup_photo_upload_mocks,
    setup_team_roster_update_mocks,
    setup_update_coach_mocks,
    setup_update_player_mocks,
)
from tests.helpers.payloads import (
    association_payload,
    invitation_relationship_and_included,
    jsonapi_detail_payload,
    jsonapi_payload,
    league_payload,
    roster_coach_payload,
    roster_player_payload,
    team_payload,
)

__all__ = [
    "ASSOCIATION_ID",
    "COACH_EXTERNAL_ID",
    "COACH_EXTERNAL_ID_SECONDARY",
    "COACH_EXTERNAL_ID_TERTIARY",
    "COACH_FIRST_NAME",
    "COACH_ID_PRIMARY",
    "COACH_ID_QUATERNARY",
    "COACH_ID_SECONDARY",
    "COACH_ID_TERTIARY",
    "COACH_LAST_NAME",
    "DEFAULT_COACH_FIRST_NAME",
    "DEFAULT_COACH_LAST_NAME",
    "DEFAULT_PLAYER_FIRST_NAME",
    "DEFAULT_PLAYER_LAST_NAME",
    "DIVISION_ID",
    "INVITATION_CODE",
    "INVITATION_ID",
    "JSONAPI_CONTENT_TYPE",
    "LEAGUE_ID",
    "PLAYER_EXTERNAL_ID",
    "PLAYER_EXTERNAL_ID_SECONDARY",
    "PLAYER_FIRST_NAME",
    "PLAYER_ID",
    "PLAYER_ID_QUATERNARY",
    "PLAYER_ID_SECONDARY",
    "PLAYER_ID_TERTIARY",
    "PLAYER_LAST_NAME",
    "PROTOTEAM_ID",
    "REFEREE_EXTERNAL_ID_PRIMARY",
    "REFEREE_EXTERNAL_ID_SECONDARY",
    "REFEREE_EXTERNAL_ID_TERTIARY",
    "REFEREE_EXTERNAL_ID_TEST",
    "SEASON_EXTERNAL_ID",
    "SEASON_ID",
    "TEAM_ID",
    "TEAM_ID_SECONDARY",
    "TEST_BASE_URL",
    "TEST_EMAIL_GENERIC",
    "TEST_EMAIL_MINIMAL",
    "TEST_EMAIL_REFEREE",
    "TIMESTAMP_2024_01_01",
    "TIMESTAMP_2024_09_01",
    "association_payload",
    "invitation_relationship_and_included",
    "jsonapi_detail_payload",
    "jsonapi_payload",
    "league_payload",
    "roster_coach_payload",
    "roster_player_payload",
    "setup_get_team_roster_mocks",
    "setup_photo_upload_mocks",
    "setup_team_roster_update_mocks",
    "setup_update_coach_mocks",
    "setup_update_player_mocks",
    "team_payload",
]
